--------------------------------------------------------------------------------
-- generated exports map for lua-aplicado/
-- This file is a part of lua-aplicado library
-- See file `COPYRIGHT` for the license and copyright information
--------------------------------------------------------------------------------
-- WARNING! Do not change manually!
--          Generated by list-exports.
--------------------------------------------------------------------------------

return
{
  LOM_ATTRS = { "lua-aplicado/expat.lua" };
  copy_file = { "lua-aplicado/shell/filesystem.lua" };
  copy_file_to_dir = { "lua-aplicado/shell/filesystem.lua" };
  copy_file_with_flag = { "lua-aplicado/shell/filesystem.lua" };
  create_email = { "lua-aplicado/shell/send_email.lua" };
  create_path_to_file = { "lua-aplicado/filesystem.lua" };
  create_symlink_from_to = { "lua-aplicado/shell/filesystem.lua" };
  csv_convert_to_table = { "lua-aplicado/csv.lua" };
  do_atomic_op_with_file = { "lua-aplicado/filesystem.lua" };
  does_file_exist = { "lua-aplicado/filesystem.lua" };
  find_all_files = { "lua-aplicado/filesystem.lua" };
  get_extension = { "lua-aplicado/filesystem.lua" };
  get_filename_from_path = { "lua-aplicado/filesystem.lua" };
  git_add_directory = { "lua-aplicado/shell/git.lua" };
  git_are_branches_different = { "lua-aplicado/shell/git.lua" };
  git_commit_with_editable_message = { "lua-aplicado/shell/git.lua" };
  git_commit_with_message = { "lua-aplicado/shell/git.lua" };
  git_config_get_remote_url = { "lua-aplicado/shell/git.lua" };
  git_exec = { "lua-aplicado/shell/git.lua" };
  git_format_command = { "lua-aplicado/shell/git.lua" };
  git_get_tracking_branch_name_of_HEAD = { "lua-aplicado/shell/git.lua" };
  git_has_untracked_files = { "lua-aplicado/shell/git.lua" };
  git_init_subtree = { "lua-aplicado/shell/git.lua" };
  git_is_directory_dirty = { "lua-aplicado/shell/git.lua" };
  git_is_dirty = { "lua-aplicado/shell/git.lua" };
  git_is_file_changed_between_revisions = { "lua-aplicado/shell/git.lua" };
  git_load_config = { "lua-aplicado/shell/git.lua" };
  git_pull_subtree = { "lua-aplicado/shell/git.lua" };
  git_push_all = { "lua-aplicado/shell/git.lua" };
  git_read = { "lua-aplicado/shell/git.lua" };
  git_remote_add = { "lua-aplicado/shell/git.lua" };
  git_remote_rm = { "lua-aplicado/shell/git.lua" };
  git_update_index = { "lua-aplicado/shell/git.lua" };
  is_directory = { "lua-aplicado/filesystem.lua" };
  load_all_files = { "lua-aplicado/filesystem.lua" };
  load_all_files_with_curly_placeholders = { "lua-aplicado/filesystem.lua" };
  luarocks_admin_exec_dir = { "lua-aplicado/shell/luarocks.lua" };
  luarocks_admin_make_manifest = { "lua-aplicado/shell/luarocks.lua" };
  luarocks_ensure_rock_not_installed_forced = { "lua-aplicado/shell/luarocks.lua" };
  luarocks_exec = { "lua-aplicado/shell/luarocks.lua" };
  luarocks_exec_dir = { "lua-aplicado/shell/luarocks.lua" };
  luarocks_exec_dir_no_sudo = { "lua-aplicado/shell/luarocks.lua" };
  luarocks_exec_no_sudo = { "lua-aplicado/shell/luarocks.lua" };
  luarocks_get_rocknames_in_manifest = { "lua-aplicado/shell/luarocks.lua" };
  luarocks_install_from = { "lua-aplicado/shell/luarocks.lua" };
  luarocks_list_rockspec_files = { "lua-aplicado/shell/luarocks.lua" };
  luarocks_load_manifest = { "lua-aplicado/shell/luarocks.lua" };
  luarocks_load_rockspec = { "lua-aplicado/shell/luarocks.lua" };
  luarocks_make_in = { "lua-aplicado/shell/luarocks.lua" };
  luarocks_pack_to = { "lua-aplicado/shell/luarocks.lua" };
  luarocks_parse_installed_rocks = { "lua-aplicado/shell/luarocks.lua" };
  luarocks_read = { "lua-aplicado/shell/luarocks.lua" };
  luarocks_remove_forced = { "lua-aplicado/shell/luarocks.lua" };
  luarocks_show_rock_dir = { "lua-aplicado/shell/luarocks.lua" };
  make_chunk_inspector = { "lua-aplicado/chunk_inspector.lua" };
  make_cookie_jar = { "lua-aplicado/web/cookie_jar.lua" };
  random_seed_from_string = { "lua-aplicado/random.lua" };
  read_file = { "lua-aplicado/filesystem.lua" };
  remote_luarocks_ensure_rock_not_installed_forced = { "lua-aplicado/shell/remote_luarocks.lua" };
  remote_luarocks_install_from = { "lua-aplicado/shell/remote_luarocks.lua" };
  remote_luarocks_list_installed_rocks = { "lua-aplicado/shell/remote_luarocks.lua" };
  remote_luarocks_remove_forced = { "lua-aplicado/shell/remote_luarocks.lua" };
  remove_file = { "lua-aplicado/shell/filesystem.lua" };
  remove_recursively = { "lua-aplicado/shell/filesystem.lua" };
  running_under_luajit = { "lua-aplicado/luajit2.lua" };
  send_email = { "lua-aplicado/shell/send_email.lua" };
  shell_escape = { "lua-aplicado/shell.lua" };
  shell_escape_many = { "lua-aplicado/shell.lua" };
  shell_escape_many_no_subst = { "lua-aplicado/shell.lua" };
  shell_escape_no_subst = { "lua-aplicado/shell.lua" };
  shell_exec = { "lua-aplicado/shell.lua" };
  shell_exec_no_subst = { "lua-aplicado/shell.lua" };
  shell_exec_remote = { "lua-aplicado/shell/remote.lua" };
  shell_format_command = { "lua-aplicado/shell.lua" };
  shell_format_command_no_subst = { "lua-aplicado/shell.lua" };
  shell_read = { "lua-aplicado/shell.lua" };
  shell_read_no_subst = { "lua-aplicado/shell.lua" };
  shell_read_remote = { "lua-aplicado/shell/remote.lua" };
  shell_wait = { "lua-aplicado/shell.lua" };
  shell_write = { "lua-aplicado/shell.lua" };
  shell_write_async = { "lua-aplicado/shell.lua" };
  shell_write_async_no_subst = { "lua-aplicado/shell.lua" };
  shell_write_no_subst = { "lua-aplicado/shell.lua" };
  splitpath = { "lua-aplicado/filesystem.lua" };
  update_file = { "lua-aplicado/filesystem.lua" };
  write_file = { "lua-aplicado/filesystem.lua" };
  xml_convert_lom = { "lua-aplicado/expat.lua" };
}
